# Generated by Django 5.0.4 on 2024-04-14 15:17

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0003_alter_currency_name_alter_currency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversionRates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rate', models.DecimalField(decimal_places=5, max_digits=20)),
                ('date', models.DateField()),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='currency_app.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='currency_app.currency')),
            ],
            options={
                'verbose_name': 'Currency Conversion Rate',
                'verbose_name_plural': 'Currency Conversion Rates',
                'ordering': ['-date'],
            },
        ),
    ]
